server:
  port: 8004

api-gateway-sdk:
  address: http://127.0.0.1:8001
  system-id: api-gateway-sdk-test
  system-name: '网关sdk测试过程'
  system-registry: zookeeper://192.168.198.138:2181
  system-address: http://127.0.0.1:8004