server:
  port: 8082

dubbo:
  registry:
    address: zookeeper://192.168.198.138:2181
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  application:
    name: api-gateway-test
    protocol: tri
    logger: slf4j
